# Generated by Django 5.2.7 on 2025-10-14 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElderlyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('check_in_interval', models.IntegerField(default=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('emergency', 'Emergency')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elderly_checkin.elderlyprofile')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_time', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('reminder_type', models.CharField(choices=[('check_in', 'Check In Reminder'), ('follow_up', 'Follow Up Reminder'), ('emergency', 'Emergency Alert')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elderly_checkin.elderlyprofile')),
            ],
        ),
    ]
